version: '3.8'

services:
# php
  app:
    container_name: php
    build: ./docker/php
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
# nginx
  # web:
  #   image: nginx:1.18
  #   ports:
  #     - '8000:80'
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/var/www/html
